server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-connections: 1000
    max-threads: 2000
    accept-count: 1500
    max-http-form-post-size: 0

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 100
        min-idle: 5
        connection-test-query: select 1
        pool-name: TRSHikariCP
      # 配置默认数据源
      primary: base
      datasource:
        # 数据源-1，名称为 base
        base:
          username: zycf
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/zycf?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
        # 数据源-2，名称为 quartz
        quartz:
          username: zycf
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/zycf?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

  redis:
    # Redis数据库索引（默认为 0）
    database: 10
    # Redis服务器地址
    host: 39.106.85.90
    # Redis服务器连接端口
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 1000
        min-idle: 5
        max-idle: 10
        max-active: 50
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000


async:
  executor:
    core:
      pool:
        size: 8

logging:
  level:
    com.trs.search.repository: WARN

# mq地址信息
rocketmq:
  nameserver: 127.0.0.1:9876
  producer:
    group: system-group
    send-message-timeout: 5000